In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data = pd.read_csv("country_vaccinations.csv")
data.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/

In [20]:
pd.to_datetime(data.date)
data.country.value_counts()

Norway                             482
Latvia                             480
Denmark                            476
United States                      471
Russia                             470
                                  ...
Bonaire Sint Eustatius and Saba    146
Tokelau                            114
Saint Helena                        92
Pitcairn                            85
Falkland Islands                    67
Name: country, Length: 223, dtype: int64

In [21]:
#The United Kingdom is made up of England, Scotland, Wales, and Northern Ireland. But in the above data
data = data[data.country.apply(lambda x: x not in ["England", "Scotland", "Wales", "Northern Ireland"])]
data.country.value_counts()

Norway                             482
Latvia                             480
Denmark                            476
United States                      471
Canada                             470
                                  ...
Bonaire Sint Eustatius and Saba    146
Tokelau                            114
Saint Helena                        92
Pitcairn                            85
Falkland Islands                    67
Name: country, Length: 219, dtype: int64

In [22]:
data.vaccines.value_counts()

Johnson&Johnson, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech                     7608
Oxford/AstraZeneca                                                                6022
Oxford/AstraZeneca, Pfizer/BioNTech                                               4629
Moderna, Oxford/AstraZeneca, Pfizer/BioNTech                                      4491
Johnson&Johnson, Moderna, Novavax, Oxford/AstraZeneca, Pfizer/BioNTech            3564
                                                                                  ...
Johnson&Johnson, Oxford/AstraZeneca, Sinovac                                       312
Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, Sputnik V                   311
Johnson&Johnson, Moderna                                                           251
Johnson&Johnson, Pfizer/BioNTech, Sinopharm/Beijing                                228
EpiVacCorona, Oxford/AstraZeneca, QazVac, Sinopharm/Beijing, Sputnik V, ZF2001     190
Name: vaccines, Length: 84, dtype: int64

In [23]:
df = data[["vaccines", "country"]]
df

                                                vaccines      country
0      Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...  Afghanistan
1      Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...  Afghanistan
2      Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...  Afghanistan
3      Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...  Afghanistan
4      Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...  Afghanistan
...                                                  ...          ...
86507  Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...     Zimbabwe
86508  Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...     Zimbabwe
86509  Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...     Zimbabwe
86510  Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...     Zimbabwe
86511  Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...     Zimbabwe

[84740 rows x 2 columns]

In [24]:
#how many countries are taking each of the vaccines mentioned in this data:
dict = {}
for i in df.vaccines.unique():
    dict[i] = [df["country"][j] for j in df[df["vaccines"]==i].index]
vaccines = {}
for key,value in dict.items():
    vaccines[key] = set(value)
for i, j in vaccines.items():
    print(f"{i}:>>{j}")

Johnson&Johnson, Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing:>>{'Belize', 'Afghanistan', 'Cameroon', 'Namibia', 'Trinidad and Tobago'}
Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, Sputnik V:>>{'Albania', 'Oman', 'Azerbaijan', 'Bosnia and Herzegovina'}
Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac, Sputnik V:>>{'Zimbabwe', 'Algeria'}
Moderna, Oxford/AstraZeneca, Pfizer/BioNTech:>>{'Japan', 'Andorra', 'United Kingdom', 'Australia', 'Finland', 'Isle of Man', 'Guernsey', 'Sweden', 'Sint Maarten (Dutch part)', 'Fiji', 'Jersey'}
Oxford/AstraZeneca:>>{'Sao Tome and Principe', 'Tuvalu', 'Falkland Islands', 'Tonga', 'Democratic Republic of Congo', 'Nigeria', 'Vanuatu', 'Nauru', 'Montserrat', 'Pitcairn', 'Saint Helena', 'Papua New Guinea', 'Liberia', 'Mali', 'Saint Vincent and the Grenadines', 'Togo', 'Solomon Islands', 'Kiribati', 'Angola', 'Samoa'}
Oxford/AstraZeneca, Pfizer/BioNTech:>>{'Saint Lucia', 'New Zealand', 'Bermuda', 'Costa Rica', 'Saudi Arabia', 'Cayman Islands', 'Saint Kitts and Nevis', 'Kosovo', 'Panama', 'Anguilla', 'Gibraltar'}
Oxford/AstraZeneca, Pfizer/BioNTech, Sputnik V:>>{'Antigua and Barbuda'}
CanSino, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sputnik V:>>{'Argentina'}
Moderna, Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac, Sputnik V:>>{'Armenia'}
Pfizer/BioNTech:>>{'Tokelau', 'Niue', 'Turks and Caicos Islands', 'New Caledonia', 'Monaco', 'Cook Islands', 'Aruba'}
Johnson&Johnson, Moderna, Novavax, Oxford/AstraZeneca, Pfizer/BioNTech:>>{'Slovenia', 'Austria', 'Germany', 'Netherlands', 'Lithuania', 'South Korea', 'Italy', 'Czechia'}
Johnson&Johnson, Oxford/AstraZeneca, Pfizer/BioNTech:>>{'Eswatini', 'Grenada', 'Bahamas'}
Johnson&Johnson, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sputnik Light, Sputnik V:>>{'Bahrain'}
Johnson&Johnson, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sinovac:>>{'Bangladesh'}
Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing:>>{'Maldives', 'Dominica', 'Peru', 'Barbados', 'Suriname'}
Sinopharm/Beijing, Sputnik V:>>{'Belarus', 'Kyrgyzstan'}
Johnson&Johnson, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech:>>{'Croatia', 'Estonia', 'Greece', 'Malta', 'Portugal', 'Romania', 'Poland', 'Iceland', 'Canada', 'Ireland', 'France', 'Jamaica', 'Bulgaria', 'Luxembourg', 'Spain', 'Cyprus', 'Belgium'}
Johnson&Johnson, Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac:>>{'Benin', 'Brazil'}
Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing:>>{'Cape Verde', 'Bhutan'}
Johnson&Johnson, Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sputnik V:>>{'Moldova', 'Bolivia', 'Morocco', "Cote d'Ivoire"}
Moderna, Pfizer/BioNTech:>>{'Curacao', 'Israel', 'Faeroe Islands', 'Qatar', 'Bonaire Sint Eustatius and Saba', 'Norway'}
Covaxin, Johnson&Johnson, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac:>>{'Botswana'}
Johnson&Johnson, Oxford/AstraZeneca:>>{'South Sudan', 'Malawi', 'British Virgin Islands'}
Johnson&Johnson, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing:>>{'Kenya', 'Brunei', 'Nepal', 'Kuwait'}
Johnson&Johnson, Oxford/AstraZeneca, Sinopharm/Beijing:>>{'Lesotho', 'Madagascar', 'Mozambique', 'Burkina Faso', 'Zambia', 'Senegal', 'Gambia'}
Sinopharm/Beijing:>>{'Burundi', 'Equatorial Guinea', 'Chad'}
Johnson&Johnson, Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac:>>{'Somalia', 'Cambodia'}
Covaxin, Oxford/AstraZeneca:>>{'Central African Republic'}
CanSino, Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac:>>{'Chile', 'Ecuador'}
CanSino, Sinopharm/Beijing, Sinopharm/Wuhan, Sinovac, ZF2001:>>{'China'}
Johnson&Johnson, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac:>>{'Uganda', 'Colombia', 'Ukraine'}
Covaxin, Oxford/AstraZeneca, Sinopharm/Beijing:>>{'Mauritius', 'Comoros'}
Moderna, Oxford/AstraZeneca, Sinopharm/Beijing, Sputnik V:>>{'Congo'}
Abdala, Soberana Plus, Soberana02:>>{'Cuba'}
Johnson&Johnson, Moderna, Pfizer/BioNTech:>>{'United States', 'Liechtenstein', 'Denmark', 'Switzerland'}
Johnson&Johnson, Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sinovac, Sputnik V:>>{'Egypt', 'Djibouti', 'Guinea'}
Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sinovac:>>{'Dominican Republic', 'El Salvador', 'Georgia'}
Covaxin, Johnson&Johnson, Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac:>>{'Ethiopia'}
Johnson&Johnson, Pfizer/BioNTech:>>{'French Polynesia', 'South Africa'}
Pfizer/BioNTech, Sinopharm/Beijing, Sputnik V:>>{'Gabon'}
Oxford/AstraZeneca, Sputnik V:>>{'Ghana'}
Moderna:>>{'Greenland', 'Wallis and Futuna'}
Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sputnik V:>>{'Guatemala'}
Oxford/AstraZeneca, Sinopharm/Beijing:>>{'Myanmar', 'Mauritania', 'Sierra Leone', 'Guinea-Bissau', 'Niger'}
Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sputnik V:>>{'Sri Lanka', 'Guyana'}
Johnson&Johnson, Moderna:>>{'Haiti'}
Johnson&Johnson, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sputnik V:>>{'Honduras'}
Pfizer/BioNTech, Sinovac:>>{'Hong Kong'}
Johnson&Johnson, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sputnik V:>>{'Hungary', 'Jordan'}
Covaxin, Oxford/AstraZeneca, Sputnik V:>>{'India'}
Johnson&Johnson, Moderna, Novavax, Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sinovac:>>{'Indonesia'}
COVIran Barekat, Covaxin, FAKHRAVAC, Oxford/AstraZeneca, Razi Cov Pars, Sinopharm/Beijing, Soberana02, SpikoGen, Sputnik V:>>{'Iran'}
Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sputnik V:>>{'Serbia', 'Lebanon', 'Montenegro', 'Iraq', 'Mongolia'}
QazVac, Sinopharm/Beijing, Sputnik V:>>{'Kazakhstan'}
Johnson&Johnson, Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sinovac, Sputnik Light, Sputnik V:>>{'Laos'}
Johnson&Johnson, Moderna, Novavax, Pfizer/BioNTech:>>{'Latvia'}
Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sinovac, Sputnik V:>>{'North Macedonia', 'Libya'}
Pfizer/BioNTech, Sinopharm/Beijing:>>{'Macao'}
CanSino, Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sinovac:>>{'Malaysia'}
CanSino, Johnson&Johnson, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, Sputnik V:>>{'Mexico'}
Abdala, Johnson&Johnson, Oxford/AstraZeneca, Pfizer/BioNTech, Soberana02, Sputnik Light, Sputnik V:>>{'Nicaragua'}
Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac:>>{'Northern Cyprus', 'Uruguay', 'Timor'}
CanSino, Covaxin, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sinovac, Sputnik V:>>{'Pakistan'}
Johnson&Johnson, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sinovac, Sputnik Light, Sputnik V:>>{'Philippines', 'Palestine'}
Covaxin, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sinovac, Sputnik V:>>{'Paraguay'}
EpiVacCorona, Sputnik V:>>{'Russia'}
Johnson&Johnson, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sinovac, Sputnik V:>>{'Rwanda', 'Tunisia'}
Pfizer/BioNTech, Sputnik V:>>{'San Marino'}
Oxford/AstraZeneca, Sinopharm/Beijing, Sputnik V:>>{'Seychelles'}
Moderna, Pfizer/BioNTech, Sinopharm/Beijing, Sinovac:>>{'Singapore'}
Johnson&Johnson, Moderna, Novavax, Oxford/AstraZeneca, Pfizer/BioNTech, Sputnik V:>>{'Slovakia'}
Johnson&Johnson, Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sinovac:>>{'Sudan'}
Johnson&Johnson, Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac, Sputnik Light, Sputnik V:>>{'Syria'}
Medigen, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech:>>{'Taiwan'}
Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, Sputnik V:>>{'Tajikistan'}
Johnson&Johnson, Pfizer/BioNTech, Sinopharm/Beijing:>>{'Tanzania'}
Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sinovac:>>{'Thailand'}
Pfizer/BioNTech, Sinovac, Turkovac:>>{'Turkey'}
EpiVacCorona, Oxford/AstraZeneca, QazVac, Sinopharm/Beijing, Sputnik V, ZF2001:>>{'Turkmenistan'}
Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sinopharm/Wuhan, Sputnik V:>>{'United Arab Emirates'}
Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, Sputnik Light, Sputnik V, ZF2001:>>{'Uzbekistan'}
Abdala, Sinopharm/Beijing, Sinovac, Soberana02, Sputnik Light, Sputnik V:>>{'Venezuela'}
Abdala, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sputnik V:>>{'Vietnam'}
Johnson&Johnson, Oxford/AstraZeneca, Sinovac:>>{'Yemen'}

In [25]:
import plotly.express as px
import plotly.offline as py

vaccine_map = px.choropleth(data, locations = 'iso_code', color = 'vaccines')
vaccine_map.update_layout(height=300, margin={"r":0,"t":0,"l":0,"b":0})
vaccine_map.show()